#common
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/common.git
  path: roles/

#forge_users
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/forge_users.git
  path: roles/

#grid
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/grid.git
  path: roles/
